services:
  # A Docker web service
  - type: web
    name: FASTAPI-RAG
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install --upgrade pip && pip install --no-deps -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8001
